### ISSUE TITLE
webSocketOnMessage

### ISSUE THREAD

**Issue by SanderPaulus** [DavidVine/amx-util-library#1]
Hi David,

I get the following error message whenever I use a webSocketOn function.
ERROR: (0): C10580: Internal Error: Major system error occurred during code generation  

Are these functions live, or am I just missing something?

Kind Regards,

Sander

![image](https://cloud.githubusercontent.com/assets/7902654/25937145/d4eed428-362a-11e7-8056-89db070aad27.png)

**Comment by DavidVine** [comment]
Hi Sander,

The "Internal Error: Major system error occurred during code generation" error is one of those errors where the compiler knows something went wrong but it can't tell you what or where.

Most of the time it is occurs due to multiple functions being declared with the same identifier.

Have you defined the associated symbol (WEBSOCKET_EVENT_OPEN) in your main program using the #DEFINE compiler directive?

If not you will certainly see that compiler error as the WebSocketOnMessage will be defined in your main code file as well as in the WebSockets include file.

Have a look at the notes at the top of the include file for implementation instructions.

Let me know if that fixes your problem.

Kind regards,

-David
avt

**Comment by SanderPaulus** [comment]
Silly mistake on my part, should have read the notes better! My apologies.

**Comment by SanderPaulus** [comment]
Hi David,

I apologize!
i did not read the notes very well.

Now compiling without errors.

Thanks for your reply.

Regards Sander

**Comment by DavidVine** [comment]
No problems Sander.

Thanks for letting me know it'a working now.

If you have any questions, just ask.

-David
avt
